### ISSUE TITLE
Make Application # 3 digits to help with sorting

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#146]
Now that we can sort by columns I realize the Application # only fills with the number of digits it creates, e.g. one digit for 1-9 and two for 10-99. This means that sorting by the Application # column puts Ayyyy-10 ahead of Ayyyy-9. So I'm guessing the field only has one digit when populated with single digit numbers. If we make the field 3 digits and fill with the appropriate sequential number then it will sort by the 3 digit number and results should be as expected.

**Comment by rarafon** [comment]
Hi Dan,
I believe I corrected it so that it will sort by the application # in #167 

Here are some screenshots of it sorting:
![sort_result_1](https://user-images.githubusercontent.com/11997170/83823963-123e6c80-a68a-11ea-887f-bce576cc52cb.png)
![sort_result_2](https://user-images.githubusercontent.com/11997170/83823968-166a8a00-a68a-11ea-9353-cec804fd8149.png)

One of them is ascending and the other is descending.

I manually edited the HTML elements by using Chrome's Dev Tool and then sorted it that way. There might be some cases that I haven't thought of for testing.

**Comment by rarafon** [comment]
I just noticed that you wanted it to be 3 digits long, but I made it so that it's using regular expressions to work with any number of digits, which is why those values in the screenshots are sorted by year and then number digits.

**Comment by dandahle** [comment]
Hi Andy - I don’t really care if it’s 3 digits or not. I was half-assed trying to solve the problem with a brute-force approach. As long as they sort properly in order, that’s the only thing that matters. Your solution sounds like what I wanted, not what I asked for, which is good. :-) Thanks for the quick work on all of this! ==> Dan

**Comment by dandahle** [comment]
Andy addressed the desired functionality in #167 so closing this and will test #167.
