### ISSUE TITLE
Partners tab in Assessments & Projects

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#266]
There is not enough space for full Partner information in the Partners tab, so eliminate the address and just show "Org Name", "Contact", "Phone", "email" and a "View" button in the Options column.  In the "View" window show the rest of the Partner information (same info as edit, but one more step to change something) and add an "Edit" button to make any changes.

**Comment by rarafon** [comment]
I created a "View" button that displays the info but I didn't add a way to go to the Edit menu since it would take a few changes. 

Did you want the edit button to go to the edit partner window? Or what did you mean by one more step?

I also added a confirmation window after editing the partner info to see if this option would work instead where the View/ Edit window can be combined.

**Comment by dandahle** [comment]
Hi Andy - I was thinking the "edit" button would be in the box that displays the info when "view" button is clicked, rather than the "edit" button showing in the Partners tab. What you have is fine, but the 'one extra step' would just avoid someone clicking "edit" instead of "view" and then changing the data.
